max_obstacle_height: 0.6
obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.18
inflation_radius: 0.50

# voxel map configuration; z-voxels 0 are filled by bumpers and 1 by laser scan (kinect)
map_type: voxel
origin_z: 0.0
z_resolution: 0.2
z_voxels: 2
publish_voxel_map: false

#unknown_threshold: 9
#mark_threshold: 0
#transform_tolerance: 0.3
#footprint: [[-0.1625, -0.1625], [-0.1625, 0.1625], [0.1625, 0.1625], [0.23, 0.0], [0.1625, -0.1625]]
#footprint_padding: 0.01
#cost_scaling_factor: 10.0
#lethal_cost_threshold: 100

observation_sources: scan

scan: {
  data_type: LaserScan,
  topic: scan,
  #expected_update_rate: 0.4,
  #observation_persistence: 0.0,
  marking: true,
  clearing: true,
  max_obstacle_height: 0.4,
  min_obstacle_height: 0.08
}